### ISSUE TITLE
Screen too big

### ISSUE THREAD

**Issue by Jalco28** [purpleysound/chess#1]
Screen is a hella big boi, too big for chess board, leaves ugly grey border

**Comment by Jalco28** [comment]
This is Agent Winksworth. Middle name... '8*64 = 512''. [Exits via helicopter]

**Comment by purpleysound** [comment]
> Screen is a hella big boi, too big for chess board, leaves ugly grey border
Hello, the screen space is reserved for future UI, as more stuff will be there in the future, but I'll make sure to make it a less ugly colour in the future. Thanks for your suggestion!

**Comment by Jalco28** [comment]
😠
